# Generated by Django 6.0.4 on 2026-04-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aluno_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='nascimento',
        ),
    ]
