# Generated by Django 5.2.13 on 2026-04-14 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola_nome', models.CharField(max_length=255, verbose_name='Nome da Escola')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('plano', models.CharField(choices=[('gratuito', 'Gratuito'), ('basico', 'Básico'), ('profissional', 'Profissional')], default='gratuito', max_length=20, verbose_name='Plano')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Usuário',
                'verbose_name_plural': 'Perfis dos Usuários',
            },
        ),
    ]
