# Generated by Django 6.0.4 on 2026-04-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_data_inicio_trial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='data_inicio_trial',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='trial_ativo',
        ),
    ]
