# Generated by Django 5.2.13 on 2026-04-14 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='data_fim_recorrencia',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fim da Recorrência'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='mensalidade_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxima_mensalidade', to='financeiro.mensalidade', verbose_name='Mensalidade Anterior'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='recorrente',
            field=models.BooleanField(default=True, verbose_name='Recorrente'),
        ),
    ]
